version: '3'

services:

  postgreSQL:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=dev-user
      - POSTGRES_PASSWORD=dev-password
      - POSTGRES_DB=workshop_app
    volumes:
      - dev-workshop-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  dev-workshop-data:

