version: '3'

volumes:
  postgresql-data:

services:

  postgreSQL:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=dev-user
      - POSTGRES_PASSWORD=dev-password
      - POSTGRES_DB=workshop_app
    volumes:
      - postgresql-data:/var/lib/postgresql
    restart: unless-stopped
